### ISSUE TITLE
Missing Header

### ISSUE THREAD

**Issue by ninryu** [Catgrills/Matcha#2]
Header image doesn't show on KissManga.

**Comment by Catgrills** [comment]
Actually, I encountered a similar issue when I was writing the script : from time to time, all the images I hosted on imgur disappear, that's why I tried to change the image host. Switching the host resolved the issue for me, that's why I'm quite surprised to hear that the issue still persist. Care to post a screenshot ?

**Comment by ninryu** [comment]
Here: https://i.imgur.com/mdHUacN.png

**Comment by ninryu** [comment]
It still doesn't work even if I use a different host site.

**Comment by oxycantha** [comment]
i have the same problem with kissmanga aswell

**Comment by Catgrills** [comment]
I think the problem was with the image hosting site : I updated the script, tell me if it solved the problem or not.

**Comment by Catgrills** [comment]
I'm beginning to run out of ideas then. Desactivate the script, and create one with only : 

@-moz-document domain("kissmanga.com") {
    :root {
        --avatar: url("https://vignette.wikia.nocookie.net/nichijou/images/e/e4/Anime-hakase-kawaii-nichijou-Favim.com-218145.jpg/revision/latest?cb=20121221073705") !important;
        --banner: url("http://stuffpoint.com/anime-and-manga/image/322583-anime-and-manga-one-piece-colorful.jpg") !important;
        --hot: url("https://s7.postimg.cc/52wxo944r/00_FJbu.png") !important;
        --link: url("http://icon-park.com/imagefiles/link_icon_blue.png") !important;
        --logo: url("https://s7.postimg.cc/x1r3fm5wp/v_RRZ6_X.png") !important;
        --next: url("https://s7.postimg.cc/stwb6i9if/Rk0_Cq3.png") !important;
        --prev: url("https://s7.postimg.cc/j9cojmrw7/tr_Eva_Q.png") !important;
        --search: url("https://www.freeiconspng.com/uploads/flat-search-find-icon-13.png") !important;
    }

	/* HEADER */
    
	/** DESCRIPTION : change the elements of the header/upper part **/
	#head h1 {
		background: no-repeat var(--banner) center !important;
		background-size: cover !important;
		border-top: 10px solid #2980b9 !important;
		border-bottom: 65px solid #2C3E50 !important;
		height: 200px !important;
		width: 100% !important;
		position: absolute !important;
		top: -30px !important;
		left: 0px !important;
	}

	#head h1 a.logo {
		background: var(--logo) no-repeat !important;
		background-size: auto 135px !important;
		width: 80% !important;
		padding-bottom: 10px !important;
		margin-top: 25px !important;
		margin-left: 20px !important;
		z-index: 9999 !important;
	}
}

If it does work, then there is something wrong with the rest of the script. Otherwise, that means that there is a problem with the code above.

**Comment by ninryu** [comment]
Yes, the header image is missing when I used that script.

**Comment by Catgrills** [comment]
Alright, now at least we know where the issue comes from. Instead, put the following code

#head h1 {
	background: no-repeat url("http://stuffpoint.com/anime-and-manga/image/322583-anime-and-manga-one-piece-colorful.jpg") center !important;
}

#head h1 a.logo {
	background: url("https://s7.postimg.cc/x1r3fm5wp/v_RRZ6_X.png") no-repeat !important;
}

If it doesn't work then there is clearly a problem.

**Comment by ninryu** [comment]
Still doesn't work.
